#!/usr/bin/env bash
# Creates a certificate using certbot and configure HAproxy to accept encrypted traffic for your subdomain www. 

DNS_info () {
  answer_section=$(dig $2.$1 | grep -A1 'ANSWER SECTION:')
  dns_record=$(echo $answer_section | awk '{print $7}')
  ip_adress=$(echo $answer_section | awk '{print $8}')
  printf "The subdomain %s is a %s record and points to %s\n" "$2" "$dns_record" "$ip_adress"
}

if [[ $# == 1 ]]; then
    subdomains=('www' 'lb-01' 'web-01' 'web-02')
    for i in "${subdomains[@]}"; do
        CONCAT="$i.$1"
        DNS_info $i $CONCAT
    done
else
    CONCAT="$2.$1"
    DNS_info $2 $CONCAT
fi

