#!/usr/bin/env bash
#Displays 'Best School 10 times'
#But for the 9th iteration, displays Best School and then Hi on a new line.

i=0
while [ $i -lt 10 ]
do
	if [ $i = 8 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((i++))
done
